apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx-app
  labels:
    app: nginx
spec:
  repliacs: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
