apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namspace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: NodePort